server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://152.136.170.48:3310/bilibili_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/bilibili_monitor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
#    password: 12345678
    password: q123456Q
    driver-class-name: com.mysql.cj.jdbc.Driver

#knife4j.enable=true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    io.github.admin4j.http.core: debug

